import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState, useMemo } from "react";
import { useQuery } from "react-query";

interface Pokemon {
  id: number;
  title: string;
  image: string;
}

const getPokemon = (): Promise<Pokemon[]> =>
  fetch("https://ghibliapi.herokuapp.com/films").then((resp) => resp.json());

export async function getServerSideProps() {
  return {
    props: {
      initialPokemon: await getPokemon()
    },
  };
}

export default function Home({ initialPokemon }: { initialPokemon: Pokemon[] }) {

  const {data:pokemon} = useQuery("pokemon",getPokemon,{initialData:initialPokemon})

  const [filter, setFilter] = useState("");

  const filteredPokemon = useMemo(() => {
    let result = initialPokemon.filter((item) =>
      item.title.toLowerCase().includes(filter.toLowerCase())
    );
    return result;
  }, [initialPokemon, filter]);

  return (
    <div className={styles.main}>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <input
          type="text"
          value={filter}
          onChange={(e) => setFilter(e.target.value)}
          className={styles.search}
        />
      </div>
      <div className={styles.container}>
        {filteredPokemon.slice(0, 20).map((p) => (
          <div key={p.id} className={styles.image}>
            <img alt={p.title} src={p.image} />
            <h2>{p.title}</h2>
          </div>
        ))}
      </div>
    </div>
  );
}
