import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState, useMemo } from "react";
import {usePokemon} from "../src/store"

export {getServerSideProps} from "../src/store"


export default function Home() {

  const {pokemon,filter,setFilter} = usePokemon()

  return (
    <div className={styles.main}>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <input
          type="text"
          value={filter}
          onChange={(e) => setFilter(e.target.value)}
          className={styles.search}
        />
      </div>
      <div className={styles.container}>
      {pokemon.slice(0, 20).map((p) => (
        <div key={p.id} className={styles.image}>
          <img
            alt={p.title}
            src={p.image}
          />
          <h2>{p.title}</h2>
        </div>
      ))}
      </div>
    </div>
  );
}
